name: Tests

on:
  push:
    branches:
      - develop
  
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to pull-requested branch
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x
      
      - name: Restore dependencies
        run: dotnet restore Tour4BD.sln

      - name: Build
        run: dotnet build Tour4BD.sln --no-restore
        
      - name: Run tests
        run: dotnet test --no-build --verbosity normal
